In [96]:
import pandas as pd
import numpy as np

#Read the csv file to df
df = pd.read_csv("heart.csv")
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [97]:
df.shape

(918, 12)

In [98]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [99]:
df[df["Cholesterol"] >(df.Cholesterol.mean() + 3*df.Cholesterol.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
76    32   M           ASY        118          529          0     Normal   
149   54   M           ASY        130          603          1     Normal   
616   67   F           NAP        115          564          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
76     130              N      0.0     Flat             1  
149    125              Y      1.0     Flat             1  
616    160              N      1.6     Flat             0

In [100]:
df1 = df[df["Cholesterol"] <(df.Cholesterol.mean() + 3*df.Cholesterol.std())]
df1.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [101]:
df[df["RestingBP"] >(df.RestingBP.mean() + 3*df.RestingBP.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
109   39   M           ATA        190          241          0     Normal   
241   54   M           ASY        200          198          0     Normal   
365   64   F           ASY        200            0          0     Normal   
399   61   M           NAP        200            0          1         ST   
592   61   M           ASY        190          287          1        LVH   
732   56   F           ASY        200          288          1        LVH   
759   54   M           ATA        192          283          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
109    106              N      0.0       Up             0  
241    142              Y      2.0     Flat             1  
365    140              Y      1.0     Flat             1  
399     70              N      0.0     Flat             1  
592    150              Y      2.0     Down             1  
732    133              Y      4.0     Down             1  
759    195              N      0.0       Up             1

In [102]:
df2 = df1[df1["RestingBP"] <(df.RestingBP.mean() + 3*df1.RestingBP.std())].copy()
df2

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[908 rows x 12 columns]

In [103]:
df[df["MaxHR"] >(df.MaxHR.mean() + 3*df.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [104]:
df[df["Oldpeak"] <=(df.Oldpeak.mean() - 3*df.Oldpeak.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
324   46   M           ASY        100            0          1         ST   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
324    133              N     -2.6     Flat             1

In [105]:
df3 = df2[df2["Oldpeak"] >=(df.Oldpeak.mean() - 3*df.Oldpeak.std())].copy()
df3

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[907 rows x 12 columns]

In [106]:
df3.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [107]:
df3.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [108]:
df3.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [109]:
df3.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [110]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [111]:
df3["Sex"] = le.fit_transform(df3["Sex"])
df3.ExerciseAngina = le.fit_transform(df3["ExerciseAngina"])
df3

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    1           ATA        140          289          0     Normal   
1     49    0           NAP        160          180          0     Normal   
2     37    1           ATA        130          283          0         ST   
3     48    0           ASY        138          214          0     Normal   
4     54    1           NAP        150          195          0     Normal   
..   ...  ...           ...        ...          ...        ...        ...   
913   45    1            TA        110          264          0     Normal   
914   68    1           ASY        144          193          1     Normal   
915   57    1           ASY        130          131          0     Normal   
916   57    0           ATA        130          236          0        LVH   
917   38    1           NAP        138          175          0     Normal   

     MaxHR  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172               0      0.0       Up             0  
1      156               0      1.0     Flat             1  
2       98               0      0.0       Up             0  
3      108               1      1.5     Flat             1  
4      122               0      0.0       Up             0  
..     ...             ...      ...      ...           ...  
913    132               0      1.2     Flat             1  
914    141               0      3.4     Flat             1  
915    115               1      1.2     Flat             1  
916    174               0      0.0     Flat             1  
917    173               0      0.0       Up             0  

[907 rows x 12 columns]

In [112]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [113]:
categorical_features = ["ChestPainType", "RestingECG", "ST_Slope"]
transformed = ColumnTransformer(
     [(
        "cat_features", OneHotEncoder(drop="first"), categorical_features
    )], remainder="passthrough"
)

In [114]:
final = transformed.fit_transform(df3)
final

array([[1. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 1. , 0. , ..., 0. , 1. , 1. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 1. , 1.2, 1. ],
       [1. , 0. , 0. , ..., 0. , 0. , 1. ],
       [0. , 1. , 0. , ..., 0. , 0. , 0. ]], shape=(907, 16))

In [115]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [116]:
data = scaler.fit_transform(final[:, :-1])
data

array([[ 2.07463095, -0.53357525, -0.23114119, ...,  1.38513966,
        -0.82251137, -0.83956058],
       [-0.48201344,  1.87414989, -0.23114119, ...,  0.7549504 ,
        -0.82251137,  0.10567458],
       [ 2.07463095, -0.53357525, -0.23114119, ..., -1.52948566,
        -0.82251137, -0.83956058],
       ...,
       [-0.48201344, -0.53357525, -0.23114119, ..., -0.85990957,
         1.21578866,  0.29472161],
       [ 2.07463095, -0.53357525, -0.23114119, ...,  1.46391332,
        -0.82251137, -0.83956058],
       [-0.48201344,  1.87414989, -0.23114119, ...,  1.42452649,
        -0.82251137, -0.83956058]], shape=(907, 15))

In [117]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [118]:
data

array([[ 2.07463095, -0.53357525, -0.23114119, ...,  1.38513966,
        -0.82251137, -0.83956058],
       [-0.48201344,  1.87414989, -0.23114119, ...,  0.7549504 ,
        -0.82251137,  0.10567458],
       [ 2.07463095, -0.53357525, -0.23114119, ..., -1.52948566,
        -0.82251137, -0.83956058],
       ...,
       [-0.48201344, -0.53357525, -0.23114119, ..., -0.85990957,
         1.21578866,  0.29472161],
       [ 2.07463095, -0.53357525, -0.23114119, ...,  1.46391332,
        -0.82251137, -0.83956058],
       [-0.48201344,  1.87414989, -0.23114119, ...,  1.42452649,
        -0.82251137, -0.83956058]], shape=(907, 15))

In [148]:
from sklearn.model_selection import cross_val_score
svm_score = np.mean(cross_val_score(SVC(),  data, final[:, -1], cv=5))
lg_score = np.mean(cross_val_score(LogisticRegression(),  data, final[:, -1], cv=5))
forest_score = np.mean(cross_val_score(RandomForestClassifier(n_estimators=150),  data, final[:, -1], cv=5))

In [149]:
svm_score

np.float64(0.8323720478416611)

In [150]:
lg_score

np.float64(0.8279582296156882)

In [151]:
forest_score

np.float64(0.8246311699350374)

In [152]:
from sklearn.decomposition import PCA

In [157]:
pc = PCA(2)
pca_data = pc.fit_transform(data)

In [159]:
svm_score = np.mean(cross_val_score(SVC(), pca_data, final[:, -1], cv=5))
svm_score

np.float64(0.8256997146499909)