In [2]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np

In [4]:
flowers = load_iris()
dir(flowers)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)
    

In [29]:
lr = []
rf = []
svms = []

In [30]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=3)
for train_index, test_index in cv.split(flowers.data, flowers.target):
    X_train, X_test, y_train, y_test = flowers.data[train_index], flowers.data[test_index], \
                                        flowers.target[train_index], flowers.target[test_index]
    lr.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))
    svms.append(get_score(SVC(), X_train, X_test, y_train, y_test))

In [36]:
print(sum(lr) / len(lr))
print(sum(rf) / len(rf))
print(sum(svms) / len(svms))

0.9733333333333333
0.9533333333333333
0.96


In [37]:
from sklearn.model_selection import cross_val_score

In [49]:
print(cross_val_score(LogisticRegression(max_iter=1000), flowers.data, flowers.target, cv=3))
print(cross_val_score(RandomForestClassifier(n_estimators=30), flowers.data, flowers.target, cv=3))
print(cross_val_score(SVC(C=1000), flowers.data, flowers.target, cv=3))

[0.98 0.96 0.98]
[0.98 0.94 0.94]
[1.   0.94 0.96]
